package com.example.know_it_all.data.remote

import com.example.know_it_all.BuildConfig // ✅ Import generated by Gradle
import com.example.know_it_all.data.remote.api.LedgerService
import com.example.know_it_all.data.remote.api.SkillService
import com.example.know_it_all.data.remote.api.SwapService
import com.example.know_it_all.data.remote.api.UserService
import com.example.know_it_all.data.local.prefs.PreferenceManager
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import java.util.concurrent.TimeUnit

object RetrofitClient {
    // ✅ This now pulls your Railway URL from local.properties via BuildConfig
    private const val BASE_URL = BuildConfig.BASE_URL

    private var preferenceManager: PreferenceManager? = null

    /**
     * ✅ Initialize this in your Application class or MainActivity
     * Example: RetrofitClient.init(PreferenceManager(this))
     */
    fun init(manager: PreferenceManager) {
        this.preferenceManager = manager
    }

    private val loggingInterceptor: HttpLoggingInterceptor by lazy {
        HttpLoggingInterceptor().apply {
            level = HttpLoggingInterceptor.Level.BODY 
        }
    }

    private val httpClient: OkHttpClient by lazy {
        OkHttpClient.Builder()
            .addInterceptor(loggingInterceptor)
            .addInterceptor { chain ->
                val original = chain.request()
                
                // ✅ Correctly access the token from the instance
                val token = preferenceManager?.getAuthToken()

                val requestBuilder = original.newBuilder()
                if (!token.isNullOrEmpty()) {
                    requestBuilder.header("Authorization", "Bearer $token")
                }
                
                chain.proceed(requestBuilder.build())
            }
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .build()
    }

    private val retrofit: Retrofit by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(httpClient)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
    }

    val userService: UserService by lazy { retrofit.create(UserService::class.java) }
    val skillService: SkillService by lazy { retrofit.create(SkillService::class.java) }
    val swapService: SwapService by lazy { retrofit.create(SwapService::class.java) }
    val ledgerService: LedgerService by lazy { retrofit.create(LedgerService::class.java) }
}